{% set version = "0.1" %}
{% set number = "1" %}
{% set build_ext_version = "1.0.0" %}
{% set build_ext = "cpu" %}
{% set build_string = "h{}_{}_{}".format(PKG_HASH, number, build_ext) %}

package:
  name: omniscidb
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ number }}
  string: "{{ build_string }}"
  script_env:
    - http_proxy
    - https_proxy

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - clangxx
    - cmake >3.14
    - llvmdev 9
    - make
    - maven
  host:
    - numpy =1.18.5
    - cython
    # omniscidb <=5.2.2 is not arrow-cpp 0.17+ ready
    - arrow-cpp =0.16
    - bisonpp
    - blosc
    - boost-cpp
    - clangdev
    - double-conversion
    - flex
    - gflags
    - glog
    - llvmdev 9
    - llvm
    - libarchive
    - libgdal
    - libkml
    - libpng
    # for some reason, librdkafka 1.4+ triggers dependency conflicts
    - librdkafka <1.4
    - ncurses
    - openldap
    - openssl
    - snappy
    - thrift-cpp
    - tbb-devel =2020.1
  # no need in run: section when using multiple outputs

outputs:
  - name: omniscidb-common
    script: install-omniscidb-common.sh
    requirements:
      build:
        - cmake >3.14  # there is no building, just copying
      run:             # common part of run requirements for other packages
        - boost-cpp
        - bzip2
        # omnscidb Load-time UDF support calls clang++
        - gxx_{{ target_platform }}
        - double-conversion
        - libgdal
        - libkml
        - libpng
        - libarchive
        - ncurses
        - openjdk 8.*
        - xz
        - zlib
        - arrow-cpp =0.16
        - tbb =2020.1

  - name: omniscidb-cpu
    script: install-omniscidb-cpu.sh
    requirements:
      build:
        - cmake >3.14  # there is no building, just copying
      run:
        - boost-cpp
        - bzip2
        # omnscidb Load-time UDF support calls clang++
        - gxx_{{ target_platform }}
        - double-conversion
        - libgdal
        - libkml
        - libpng
        - libarchive
        - ncurses
        - openjdk 8.*
        - xz
        - zlib
        - arrow-cpp =0.16
        - tbb =2020.1
        - {{ pin_subpackage('omniscidb-common', exact=True) }}
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}
    test:
      commands:
        - omnisql -v
        - which omnisci_initdb
        - which omnisci_server

  - name: omniscidbe
    script: install-omniscidbe.sh
    requirements:
      build:
        - cmake >3.14
      run:
        - {{ pin_subpackage('omniscidb-common', exact=True) }}

  - name: omniscidbe4py
    script: install-omniscidbe4py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}   # this section really builds
        - clangdev
        - clangxx
        - cmake > 3.14
        - llvmdev 9
        - make
        - maven
      host:
        - numpy =1.18.5
        - cython
        # omniscidb <=5.2.2 is not arrow-cpp 0.17+ ready
        - arrow-cpp =0.16
        - bisonpp
        - blosc
        - boost-cpp
        - clangdev
        - double-conversion
        - flex
        - gflags
        - glog
        - llvmdev 9
        - llvm
        - libarchive
        - libgdal
        - libkml
        - libpng
        # for some reason, librdkafka 1.4+ triggers dependency conflicts
        - librdkafka <1.4
        - ncurses
        - openldap
        - openssl
        - snappy
        - thrift-cpp
        - tbb-devel =2020.1
        - python
        - cython
        - numpy =1.18.5
        - pyarrow =0.16
        - {{ pin_subpackage('omniscidbe', exact=True) }}
      run:
        - pyarrow =0.16
        - tbb4py =2020.1
        - {{ pin_subpackage('omniscidbe', exact=True) }}
        - {{ pin_subpackage('omniscidb-common', exact=True) }}
    test:
      imports:
        - dbe

test:
  commands:
    # Verify the activation scripts are in-place.
    {% for state in ["activate", "deactivate"] %}
    - test -f "${PREFIX}/etc/conda/{{ state }}.d/{{ PKG_NAME }}_{{ state }}.sh"
    {% endfor %}
    # Try using the activation scripts.
    - |
      if [[ -x "$(command -v omnisql)" ]]
      then
        echo "Found omnisql in PATH"
      else
        echo "omnisql not found in PATH(=$PATH)" && exit 1
      fi
      source ${PREFIX}/etc/conda/deactivate.d/{{ PKG_NAME }}_deactivate.sh
      if [[ -x "$(command -v omnisql)" ]]
      then
        echo "Unexpectedly found omnisql in PATH(=$PATH) after deactivation"  && exit 1
      else
        echo "omnisql not in PATH after deactivation"
      fi
      source ${PREFIX}/etc/conda/activate.d/{{ PKG_NAME }}_activate.sh
    # Test installation
    - omnisql -v
    - which omnisci_initdb
    - which omnisci_server
    - |
      if [ -x "$(command -v nvidia-smi)" ]; then  # [cuda_compiler_version not in (undefined, "None")]
        mkdir data && omnisci_initdb data
        omnisci_server --version
        rm -rf data
      fi                                          # [cuda_compiler_version not in (undefined, "None")]
    - which omnisci_insert_sample_data
    - which startomnisci

about:
  home: https://www.omnisci.com/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.md
  summary: 'The OmniSci database'

  description: |
    LEGAL NOTICE: Use of this software package is subject to the software license
    agreement (as set forth above, in the license section of the installed Conda
    package and/or the README file) and all notices, disclaimers or license terms for
    third party or open source software included in or with the software.
    Third party programs: https://github.com/intel-go/omniscidb/blob/conda_build_changes/tpp.txt
  doc_url: https://www.omnisci.com/docs/latest/
  dev_url: https://github.com/omnisci/omniscidb

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
    - andrewseidl
